# Generated by Django 5.2.5 on 2025-08-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_level', models.IntegerField()),
                ('tile_x', models.IntegerField()),
                ('tile_y', models.IntegerField()),
                ('cluster_events', models.ManyToManyField(related_name='clusters', to='events.event')),
                ('representative_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['zoom_level', 'tile_x', 'tile_y'], name='events_clus_zoom_le_c3a627_idx')],
                'unique_together': {('zoom_level', 'tile_x', 'tile_y', 'representative_event')},
            },
        ),
    ]
